In [3]:
import tensorflow as tf
import numpy as np

In [3]:
tensor_two_d = tf.constant([[1,-2,0],
                            [3,5,100],
                            [1,5,6]], dtype = tf.float32)

In [3]:
s, u,v = tf.linalg.svd(tensor_two_d)

In [4]:
print(s)
print(u)
print(v)

tf.Tensor([100.3663      5.1059036   1.2371687], shape=(3,), dtype=float32)
tf.Tensor(
[[-7.4980810e-04 -3.7569830e-01  9.2674178e-01]
 [ 9.9803799e-01 -5.8300879e-02 -2.2827482e-02]
 [ 6.2606096e-02  9.2490643e-01  3.7500489e-01]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 0.03044816  0.07330841  0.99684453]
 [ 0.0528536   0.9957936  -0.07484547]
 [ 0.998138   -0.05496572 -0.02644547]], shape=(3, 3), dtype=float32)


In [6]:
import numpy as np

In [11]:
A = np.array([[2,6,5,2],
              [2,-2,2,3],
              [1,4,5,0]])

B = np.array([[2,9,0,3,0],
              [3,6,8,-2,2],
              [1,3,5,0,1],
              [3,0,2,0,5]])

print(A.shape)
print(B.shape)
print('Matmul c=:\n')
print(np.matmul(A,B),'\n')

print('Einsum c: \n')
print(np.einsum('ij,jk -> ik',A,B))

(3, 4)
(4, 5)
Matmul c=:

[[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [19 48 57 -5 13]] 

Einsum c: 

[[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [19 48 57 -5 13]]


In [13]:
A = np.array([[2,6,5,2],
              [2,-2,2,3],
              [1,5,4,0]])

B = np.array([[2,9,0,3],
              [3,6,8,-2],
              [1,3,5,0],
              ])

print(A.shape, B.shape)

print('Hardamond c=:\n')
print(A*B,'\n')

print('Einsum c: \n')
print(np.einsum('ij,ij -> ij', A,B))

(3, 4) (3, 4)
Hardamond c=:

[[  4  54   0   6]
 [  6 -12  16  -6]
 [  1  15  20   0]] 

Einsum c: 

[[  4  54   0   6]
 [  6 -12  16  -6]
 [  1  15  20   0]]


In [19]:
A = np.array([[2,6,5,2],
              [2,-2,2,3],
              [1,5,4,0]])
print('Transpose A is:\n',A.T)
print('Einsun Transpose A: \n')
print(np.einsum('ij -> ji', A))

Transpose A is:
 [[ 2  2  1]
 [ 6 -2  5]
 [ 5  2  4]
 [ 2  3  0]]
Einsun Transpose A: 

[[ 2  2  1]
 [ 6 -2  5]
 [ 5  2  4]
 [ 2  3  0]]


In [7]:
A = np.array([
             [[2,6,5,2],
              [2,-2,2,3],
              [1,4,5,0]],

             [[1,3,1,22],
              [0,2,2,0],
              [1,5,4,1]]
             ])

B = np.array([
             [[2,9,0,3,0],
              [3,6,8,-2,2],
              [1,3,5,0,1],
              [3,0,2,0,5]],

             [[1,0,0,3,0],
              [3,0,4,-2,2],
              [1,0,2,0,0],
              [3,0,1,1,0]]
             ])

print(A.shape, B.shape)
print('batch Matmul c=:\n')
print(np.matmul(A,B),'\n')

print('Einsum c: \n')
print(np.einsum('bij,bjk -> bik',A,B))

(2, 3, 4) (2, 4, 5)
batch Matmul c=:

[[[33 69 77 -6 27]
  [ 9 12  0 10 13]
  [19 48 57 -5 13]]

 [[77  0 36 19  6]
  [ 8  0 12 -4  4]
  [23  0 29 -6 10]]] 

Einsum c: 

[[[33 69 77 -6 27]
  [ 9 12  0 10 13]
  [19 48 57 -5 13]]

 [[77  0 36 19  6]
  [ 8  0 12 -4  4]
  [23  0 29 -6 10]]]


In [5]:
A = np.array([
             [[2,6,5,2],
              [2,-2,2,3],
              [1,4,5,0]],

             [[1,3,1,22],
              [0,2,2,0],
              [1,5,4,1]]
             ])
print('sum A: \n')
print(np.sum(A))

print('Einsum c: \n')
print(np.einsum('bij -> ',A))

sum A: 

72
Einsum c: 

72


In [6]:
A = np.array([[2,6,5,2],
              [2,-2,2,3],
              [1,5,4,0]])

print(np.einsum('ij -> j',A))

print(np.einsum('ij -> i',A))

print()

[ 5  9 11  5]
[15  5 10]



In [7]:
Q = np.random.randn(32,64,512)    #bqm
K = np.random.randn(32,128,512)   #bkm

np.einsum('bqm,bkm -> bqk', Q,K)

np.einsum('bqm,bkm -> bqk', Q,K).shape

(32, 64, 128)

In [8]:
A = np.random.randn(2, 4, 4, 2)    #bcij
B = np.random.randn(2, 4, 4, 1)    #bcik

In [9]:
np.einsum('bcik,bcij -> bckj', A,B)

array([[[[ 3.68467995],
         [-2.56107336]],

        [[ 2.05097089],
         [-0.33529391]],

        [[ 0.82736443],
         [-0.57423837]],

        [[ 1.50753944],
         [-1.85049395]]],


       [[[ 1.46561369],
         [-0.26998434]],

        [[-2.20477918],
         [-5.5310683 ]],

        [[ 0.85690681],
         [ 0.34837887]],

        [[-1.036535  ],
         [ 4.12508242]]]])

In [10]:
np.einsum('bcik,bcij -> bckj', B,A).shape

(2, 4, 1, 2)

In [13]:
A = np.random.randn(2, 4, 6, 4, 2)    #bcij
B = np.random.randn(2, 4, 6, 4, 1)    #bcik
np.einsum('bcdik,bcdij -> bcdkj', B, A).shape

(2, 4, 6, 1, 2)

In [14]:
np.matmul(np.transpose(B, (0,1,2,4,3)), A).shape

(2, 4, 6, 1, 2)

In [9]:
tensor_three_d = tf.constant([
                             [[1,2,0],
                              [3,5,-1]],

                             [[10,2,0],
                              [1,0,2]],

                             [[5,8,0],
                              [2,7,0]],

                             [[2,1,9],
                              [4,-3,32]]
                             ])
print(tensor_three_d.shape)
print(tf.expand_dims(tensor_three_d, axis = 0).shape)
print(tf.expand_dims(tensor_three_d, axis = 3).shape)

(4, 2, 3)
(1, 4, 2, 3)
(4, 2, 3, 1)


In [13]:
x1 = tf.constant([2,3,4,5])
x2 = tf.constant([[2,3,4,5]])
x3 = tf.constant([[[2,3,4,5]]])
print(x1.shape, x2.shape, x3.shape)
x_expanded = tf.expand_dims(x3, axis = 0)
print(tf.expand_dims(x3,axis = 3))
print(x_expanded)


(4,) (1, 4) (1, 1, 4)
tf.Tensor(
[[[[2]
   [3]
   [4]
   [5]]]], shape=(1, 1, 4, 1), dtype=int32)
tf.Tensor([[[[2 3 4 5]]]], shape=(1, 1, 1, 4), dtype=int32)


In [15]:
x_squeezed = tf.squeeze(x_expanded, axis = 0)
for i in range(2):
  x_squeezed = tf.squeeze(x_squeezed, axis = 0)
print(x_squeezed)

tf.Tensor([2 3 4 5], shape=(4,), dtype=int32)


In [17]:
x_exp = tf.expand_dims(tensor_three_d, axis = 3)
print(x_expanded.shape)
print(tf.squeeze(x_exp, axis = 3))

(1, 1, 1, 4)
tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [18]:
print(tf.reshape(x_exp, [4,2,3]).shape)

(4, 2, 3)


In [19]:
x_reshape = tf.constant([[3,5,6,6],
                         [4,6,-1,2]])
tf.reshape(x_reshape, [8,])

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([ 3,  5,  6,  6,  4,  6, -1,  2], dtype=int32)>

In [22]:
tf.reshape(x_reshape,[4,2])

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 3,  5],
       [ 6,  6],
       [ 4,  6],
       [-1,  2]], dtype=int32)>

In [25]:
print(tf.reshape(x_reshape,[4,2,1]))
print(tf.reshape(x_reshape,[4,-1]))

tf.Tensor(
[[[ 3]
  [ 5]]

 [[ 6]
  [ 6]]

 [[ 4]
  [ 6]]

 [[-1]
  [ 2]]], shape=(4, 2, 1), dtype=int32)
tf.Tensor(
[[ 3  5]
 [ 6  6]
 [ 4  6]
 [-1  2]], shape=(4, 2), dtype=int32)


In [26]:
tf.reshape(x_reshape,[-1])

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([ 3,  5,  6,  6,  4,  6, -1,  2], dtype=int32)>

In [27]:
tf.reshape(x_reshape,[8])

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([ 3,  5,  6,  6,  4,  6, -1,  2], dtype=int32)>

In [30]:
t1 = [[1,2,3],
      [4,5,6]]

t2 = [[7,8,9],
      [10,11,12]]

print(tf.constant(t1).shape)
print(tf.constant(t2).shape)

print(tf.concat([t1,t2], axis = 0))

print(tf.concat([t1,t2], axis = 1))

(2, 3)
(2, 3)
tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]], shape=(2, 6), dtype=int32)


In [3]:
t1 = [[[1,2,3],
      [4,5,6]]]

t2 = [[[7,8,9],
      [10,11,12]]]

print(tf.constant(t1).shape)
print(tf.constant(t2).shape)

print(tf.concat([t1,t2], axis = 0))
print(tf.concat([t1,t2], axis = 1))
print(tf.concat([t1,t2], axis = 2))

(1, 2, 3)
(1, 2, 3)
tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)
tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]], shape=(1, 4, 3), dtype=int32)
tf.Tensor(
[[[ 1  2  3  7  8  9]
  [ 4  5  6 10 11 12]]], shape=(1, 2, 6), dtype=int32)


In [9]:
t1 = [[1,2,3],
      [4,5,6]]

t2 = [[7,8,9],
      [10,11,12]]

print(tf.stack([t1,t2], axis = 2))

print(tf.stack([t1,t2,t1], axis = 0))

tf.Tensor(
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]], shape=(2, 3, 2), dtype=int32)
tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]]], shape=(3, 2, 3), dtype=int32)


In [10]:
tf.stack([t1,t2,t1], axis = 1)

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 7,  8,  9],
        [ 1,  2,  3]],

       [[ 4,  5,  6],
        [10, 11, 12],
        [ 4,  5,  6]]], dtype=int32)>

In [12]:
tf.stack([t1,t2,t1], axis = 2)

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 1,  7,  1],
        [ 2,  8,  2],
        [ 3,  9,  3]],

       [[ 4, 10,  4],
        [ 5, 11,  5],
        [ 6, 12,  6]]], dtype=int32)>

In [15]:
tf.concat([tf.expand_dims(t,axis = 0) for t in [t1,t2]], axis =0)

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [16]:
t = tf.constant([[1, 2, 3], [4, 5, 6]])
paddings = tf.constant([[1, 1,], [2, 2]])

tf.pad(t, paddings, "CONSTANT")

<tf.Tensor: shape=(4, 7), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 2, 3, 0, 0],
       [0, 0, 4, 5, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]], dtype=int32)>

In [17]:
tf.pad(t, paddings, "CONSTANT", constant_values=3)

<tf.Tensor: shape=(4, 7), dtype=int32, numpy=
array([[3, 3, 3, 3, 3, 3, 3],
       [3, 3, 1, 2, 3, 3, 3],
       [3, 3, 4, 5, 6, 3, 3],
       [3, 3, 3, 3, 3, 3, 3]], dtype=int32)>

In [18]:
t = tf.constant([[1, 2, 3],
                 [4, 5, 6]])

paddings = tf.constant([[1, 3,],
                        [3, 2]])

tf.pad(t, paddings, "CONSTANT")

<tf.Tensor: shape=(6, 8), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 2, 3, 0, 0],
       [0, 0, 0, 4, 5, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>

In [21]:
params = tf.constant(['p0', 'p1', 'p2', 'p3', 'p4', 'p5'])
params[1:3+1]

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p1', b'p2', b'p3'], dtype=object)>

In [22]:
tf.gather(params, [1,2,3])

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p1', b'p2', b'p3'], dtype=object)>

In [23]:
tf.gather(params, tf.range(1,4))

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p1', b'p2', b'p3'], dtype=object)>

In [24]:
tf.gather(params, [0,5,3])

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p0', b'p5', b'p3'], dtype=object)>

In [30]:
params = tf.constant([[0,1,2],
                      [10,11,12],
                      [20,21,22],
                      [30,31,32]])
tf.gather(params, [0])

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[0, 1, 2]], dtype=int32)>

In [31]:
print(params.shape)

(4, 3)


In [32]:
tf.gather(params, [0,3], axis =0)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 0,  1,  2],
       [30, 31, 32]], dtype=int32)>

In [34]:
tf.gather(params, [0,2], axis =1)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 0,  2],
       [10, 12],
       [20, 22],
       [30, 32]], dtype=int32)>

In [35]:
tf.gather(params, [2,0], axis =1)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 2,  0],
       [12, 10],
       [22, 20],
       [32, 30]], dtype=int32)>

In [38]:
params = tf.constant([
                     [[0,1,2],
                      [10,11,12],
                      [20,21,22],
                      [30,31,32]],

                     ])
print(params.shape)
tf.gather(params, [0], axis =0)

(1, 4, 3)


<tf.Tensor: shape=(1, 4, 3), dtype=int32, numpy=
array([[[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22],
        [30, 31, 32]]], dtype=int32)>

In [39]:
tf.gather(params, [2,0], axis = 1)

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[20, 21, 22],
        [ 0,  1,  2]]], dtype=int32)>

In [40]:
params = tf.constant([
                     [[0,1,2],
                      [10,11,12],
                      [20,21,22],
                      [30,31,32]],

                     [[3,1,21],
                      [1,3,88],
                      [0,5,55],
                      [0,2,30]]
                     ])
print(params.shape)
tf.gather(params, [2,0], axis =1)

(2, 4, 3)


<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[20, 21, 22],
        [ 0,  1,  2]],

       [[ 0,  5, 55],
        [ 3,  1, 21]]], dtype=int32)>

In [42]:
tf.gather(params, [1,0], axis =0)

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 3,  1, 21],
        [ 1,  3, 88],
        [ 0,  5, 55],
        [ 0,  2, 30]],

       [[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22],
        [30, 31, 32]]], dtype=int32)>

In [43]:
tf.gather(params, [2,0], axis =1)

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[20, 21, 22],
        [ 0,  1,  2]],

       [[ 0,  5, 55],
        [ 3,  1, 21]]], dtype=int32)>

In [3]:
indices = [[0],
           [1]]

params = [['a', 'b'],
          ['c', 'd']]
tf.gather_nd(params, indices)

<tf.Tensor: shape=(2, 2), dtype=string, numpy=
array([[b'a', b'b'],
       [b'c', b'd']], dtype=object)>

In [4]:
indices = [[2,1]]

params = [['a', 'b'],
          ['c', 'd'],
          ['e', 'f']]
tf.gather_nd(params, indices)

<tf.Tensor: shape=(1,), dtype=string, numpy=array([b'f'], dtype=object)>

In [5]:
indices = [[2]]

params = [['a', 'b'],
          ['c', 'd'],
          ['e', 'f']]
tf.gather_nd(params, indices)

<tf.Tensor: shape=(1, 2), dtype=string, numpy=array([[b'e', b'f']], dtype=object)>

In [6]:
indices = [2,1]

params = [['a', 'b'],
          ['c', 'd'],
          ['e', 'f']]
tf.gather_nd(params, indices)

<tf.Tensor: shape=(), dtype=string, numpy=b'f'>

In [7]:
tf.gather(params, indices)

<tf.Tensor: shape=(2, 2), dtype=string, numpy=
array([[b'e', b'f'],
       [b'c', b'd']], dtype=object)>

In [8]:
indices = [[0, 1], [1, 0]]

params = [[['a0', 'b0'],
           ['c0', 'd0']],

          [['a1', 'b1'],
           ['c1', 'd1']]]
tf.gather_nd(params, indices)

<tf.Tensor: shape=(2, 2), dtype=string, numpy=
array([[b'c0', b'd0'],
       [b'a1', b'b1']], dtype=object)>

In [9]:
indices = [[0, 1, 0], [1, 0, 1]]

params = [[['a0', 'b0'],
           ['c0', 'd0']],

          [['a1', 'b1'],
           ['c1', 'd1']]]
tf.gather_nd(params, indices)

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'c0', b'b1'], dtype=object)>

In [12]:
indices = [[[0, 1],
            [1, 0]],

           [[0, 0],
            [1, 1]]]

params = [[['a0', 'b0'],
           ['c0', 'd0']],

          [['a1', 'b1'],
           ['c1', 'd1']]]

tf.gather_nd(params, indices)

<tf.Tensor: shape=(2, 2, 2), dtype=string, numpy=
array([[[b'c0', b'd0'],
        [b'a1', b'b1']],

       [[b'a0', b'b0'],
        [b'c1', b'd1']]], dtype=object)>

In [13]:
indices = [[0, 1],
            [1, 0]]

params = [[['a0', 'b0'],
           ['c0', 'd0']],

          [['a1', 'b1'],
           ['c1', 'd1']]]

tf.gather_nd(params, indices, batch_dims = 0)

<tf.Tensor: shape=(2, 2), dtype=string, numpy=
array([[b'c0', b'd0'],
       [b'a1', b'b1']], dtype=object)>

In [14]:
indices = [[0, 1],
            [1, 0]]

params = [[['a0', 'b0'],
           ['c0', 'd0']],

          [['a1', 'b1'],
           ['c1', 'd1']]]

tf.gather_nd(params, indices, batch_dims = 1)

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'b0', b'c1'], dtype=object)>

In [15]:
indices = [[[0, 1],
            [1, 0]],

           [[0, 0],
            [1, 1]]]

params = [[['a0', 'b0'],
           ['c0', 'd0']],

          [['a1', 'b1'],
           ['c1', 'd1']]]

tf.gather_nd(params, indices, batch_dims=1)

<tf.Tensor: shape=(2, 2), dtype=string, numpy=
array([[b'b0', b'c0'],
       [b'a1', b'd1']], dtype=object)>

In [16]:
tensor_two_d = tf.constant([
                            [1,2,0],
                            [3,5,-1],
                            [1,5,5],
                            [2,3,8]
                            ])
print(tensor_two_d.shape)

(4, 3)


In [3]:
tensor_two_d = [[1,2,0],
                [3,],
                [1,5,6,5,6],
                [2,3]]

tensor_ragged = tf.ragged.constant(tensor_two_d)
print(tensor_ragged.shape)
print(tensor_ragged)

(4, None)
<tf.RaggedTensor [[1, 2, 0], [3], [1, 5, 6, 5, 6], [2, 3]]>


In [4]:
print(tensor_two_d)

[[1, 2, 0], [3], [1, 5, 6, 5, 6], [2, 3]]


In [5]:
print(tf.constant(tensor_two_d))

ValueError: Can't convert non-rectangular Python sequence to Tensor.

In [6]:
print(tf.RaggedTensor.from_row_lengths(
    values=[3,1,4,1,5,9,2,6],
    row_lengths=[4,0,3,1,0]))

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


In [7]:
tensor_sparse = tf.SparseTensor(
    indices=[[1,1],[3,4]], values = [11,56], dense_shape = [5,6]
)

In [8]:
print(tensor_sparse)

SparseTensor(indices=tf.Tensor(
[[1 1]
 [3 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([11 56], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))


In [9]:
tf.sparse.to_dense(tensor_sparse)

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  0,  0,  0,  0,  0],
       [ 0, 11,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 56,  0],
       [ 0,  0,  0,  0,  0,  0]], dtype=int32)>

In [10]:
tensor_string = tf.constant(['hello', 'i am', 'a string'])
print(tensor_string)

tf.Tensor([b'hello' b'i am' b'a string'], shape=(3,), dtype=string)


In [14]:
tf.strings.join(tensor_string, separator ="")

<tf.Tensor: shape=(), dtype=string, numpy=b'helloi ama string'>

In [15]:
tf.strings.join(tensor_string, separator =' ')

<tf.Tensor: shape=(), dtype=string, numpy=b'hello i am a string'>

In [16]:
tf.strings.join(tensor_string, separator ="**")

<tf.Tensor: shape=(), dtype=string, numpy=b'hello**i am**a string'>

In [4]:
x = tf.constant([1,2])

In [5]:
x_var = tf.Variable(x)
print(x_var)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>


In [6]:
x_var = tf.Variable(x, name = 'var1')
print(x_var)

<tf.Variable 'var1:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>


In [7]:
x_var.assign_sub([3,4])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([-2, -2], dtype=int32)>

In [8]:
x_var.assign_add([5,8])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([3, 6], dtype=int32)>

In [9]:
with tf.device('GPU:0'):
  x_var = tf.Variable(0.2)

print(x_var)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.20000000298023224>


In [10]:
print(x_var.device)

/job:localhost/replica:0/task:0/device:CPU:0


In [11]:
with tf.device('GPU:0'):
  x_var = tf.Variable(0.2)

with tf.device('CPU:0'):
  x_tensor = tf.constant(0.2)

print(x_var.device)

print(x_tensor.device)

/job:localhost/replica:0/task:0/device:CPU:0
/job:localhost/replica:0/task:0/device:CPU:0


In [12]:
with tf.device('CPU:0'):
  x_1 = tf.constant([1,3,4])
  x_2 = tf.constant([1])

with tf.device('GPU:0'):
  x_3 = x_1 + x_2

print(x_1, x_1.device)
print(x_2, x_2.device)
print(x_3, x_3.device)

tf.Tensor([1 3 4], shape=(3,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor([1], shape=(1,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor([2 4 5], shape=(3,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
