In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)


tf.Tensor(4, shape=(), dtype=int32)


In [3]:
tensor_bool = tf.constant([True, True, False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [ ]:
tensor_string = tf.constant(["hello world", "hi"])
print(tensor_string)

tf.Tensor([b'hello world' b'hi'], shape=(2,), dtype=string)


In [ ]:
tensor_one_d = tf.constant([2,0.,-3,8,90.], dtype = tf.float32)

casted_tensor_one_d = tf.cast(tensor_one_d,dtype = tf.bool)
print(tensor_one_d)
print(casted_tensor_one_d)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)
tf.Tensor([ True False  True  True  True], shape=(5,), dtype=bool)


In [6]:
tensor_two_d = tf.constant([
                            [1,2,0],
                            [3,5,-1],
                            [1,5,5],
                            [2,3,8]
                            ])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  5]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [7]:
tensor_three_d = tf.constant([
                             [[1,2,0],
                              [3,5,-1]],

                             [[10,2,0],
                              [1,0,2]],

                             [[5,8,0],
                              [2,7,0]],

                             [[2,1,9],
                              [4,-3,32]]
                             ])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
tensor_three_d.shape

TensorShape([4, 2, 3])

In [ ]:
tensor_zero_d.shape

TensorShape([])

In [ ]:
tensor_three_d.ndim

3

In [ ]:
tensor_four_d = tf.constant([
 [
    [[1,2,0],
    [3,5,-1]],

    [[10,2,0],
    [1,0,2]],

    [[5,8,0],
    [2,7,0]],

    [[2,1,9],
    [4,-3,32]]
],
[
  [[13,26,0],
    [3,5,-12]],

    [[10,2,0],
    [1,0,23]],

    [[5,8,0],
    [2,73,0]],

    [[2,1,9],
    [4,-30,32]],
],
[
  [[103,26,0],
    [3,50,-12]],

    [[100,2,0],
    [1,0,23]],

    [[5,28,0],
    [2,3,0]],

    [[22,1,9],
    [44,-320,32]],
]
])
print(tensor_four_d)

tf.Tensor(
[[[[   1    2    0]
   [   3    5   -1]]

  [[  10    2    0]
   [   1    0    2]]

  [[   5    8    0]
   [   2    7    0]]

  [[   2    1    9]
   [   4   -3   32]]]


 [[[  13   26    0]
   [   3    5  -12]]

  [[  10    2    0]
   [   1    0   23]]

  [[   5    8    0]
   [   2   73    0]]

  [[   2    1    9]
   [   4  -30   32]]]


 [[[ 103   26    0]
   [   3   50  -12]]

  [[ 100    2    0]
   [   1    0   23]]

  [[   5   28    0]
   [   2    3    0]]

  [[  22    1    9]
   [  44 -320   32]]]], shape=(3, 4, 2, 3), dtype=int32)


In [4]:
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [5]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


In [6]:
eye_tensor = tf.eye(
      num_rows = 5,
      num_columns=None,
      batch_shape=None,
      dtype=tf.dtypes.float32,
      name=None)

print(eye_tensor)
print(3*eye_tensor)

tf.Tensor(
[[[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]], shape=(2, 4, 5, 5), dtype=float32)
tf.Tensor(
[[[[3. 0. 0. 0. 0.]
   [0. 3. 0. 0. 0.]
   [0. 0. 3. 0. 0.]
   [0. 0. 0. 3. 0.]
   [0. 0. 0. 0. 3.]]

  [[3. 0. 0. 0. 0.]
 

In [8]:
eye_tensor = tf.eye(
      num_rows = 5,
      num_columns=None,
      batch_shape=[2,],
      dtype=tf.dtypes.float32,
      name=None)

print(eye_tensor)

tf.Tensor(
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]], shape=(2, 5, 5), dtype=float32)


In [9]:
eye_tensor = tf.eye(
      num_rows = 5,
      num_columns=None,
      batch_shape=[2,4],
      dtype=tf.dtypes.float32,
      name=None)

print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]], shape=(2, 4, 5, 5), dtype=float32)


In [5]:
fill_tensor = tf.fill(
    [2,3,4],5, name = None
)
print(fill_tensor)

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(2, 3, 4), dtype=int32)


In [3]:
ones_tensor = tf.ones(
    [5,3,2],
    dtype = tf.dtypes.float32,
    name = None
)
print(ones_tensor)

tf.Tensor(
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]], shape=(5, 3, 2), dtype=float32)


In [6]:
 ones_like_tensor = tf.ones_like(fill_tensor)
 print(ones_like_tensor)

tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]], shape=(2, 3, 4), dtype=int32)


In [7]:
zeros_tensor = tf.zeros(
    [3,2],
    dtype = tf.dtypes.float32,
    name = None
)
print(zeros_tensor)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [8]:
print(zeros_tensor.shape)

(3, 2)


In [9]:
print(tf.shape(zeros_tensor))

tf.Tensor([3 2], shape=(2,), dtype=int32)


In [10]:
# shape of tensor 't' is [2, 2, 3]
t = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])
tf.rank(t)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [11]:
# shape of tensor 't' is [2, 2, 3]
t = tf.constant([[1, 1, 1], [2, 2, 2]])
tf.rank(t)  # 3

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [2]:
t = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])
tf.size(t)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [4]:
t = tf.constant([[1, 1, 1], [2, 2, 2]],)
tf.size(t, out_type=tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [12]:
random_tensor = tf.random.normal(
    [3,2],
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[-0.5624743  -0.92763674]
 [ 1.5136944  -0.15361713]
 [-0.19454901  1.1426387 ]], shape=(3, 2), dtype=float32)
