<a href="https://colab.research.google.com/github/FRashidy1403/Deep-learning-for-computer-vision/blob/main/Second_H_of_37_Hours.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
random_tensor = tf.random.uniform(
    [1,],
    minval=0,
    maxval=None,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor([0.75369334], shape=(1,), dtype=float32)


In [ ]:
random_tensor = tf.random.uniform(
    [5,],
    minval=0,
    maxval=8,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor([0.11099434 2.476943   4.2739344  5.635515   4.415742  ], shape=(5,), dtype=float32)


In [ ]:
random_tensor = tf.random.uniform(
    [5,],
    minval=0,
    maxval=100,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor([16.70401 32.97578 91.32188 69.44425 84.97575], shape=(5,), dtype=float32)


In [ ]:
random_tensor = tf.random.uniform(
    [5,],
    minval=0,
    maxval=100,
    dtype=tf.dtypes.int32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor([ 0 20 48 94 10], shape=(5,), dtype=int32)


In [ ]:
random_tensor = tf.random.uniform([5,],
    minval=0,
    maxval=None,
    dtype=tf.dtypes.int32,
    seed=None,
    name=None
)
print(random_tensor)

ValueError: Must specify maxval for integer dtype tf.int32

In [ ]:
random_tensor = tf.random.uniform(
    [5,5],
    minval=0,
    maxval=1000,
    dtype=tf.dtypes.int32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[440 908 403 455 196]
 [922 735 417 496  62]
 [689 703 146 493 321]
 [956 328 112 134 446]
 [528 775 275 566 271]], shape=(5, 5), dtype=int32)


In [ ]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)


In [ ]:
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))

tf.Tensor([4 2 2], shape=(3,), dtype=int32)
tf.Tensor([4 2 1], shape=(3,), dtype=int32)
tf.Tensor([4 1 0], shape=(3,), dtype=int32)
tf.Tensor([1 2 1], shape=(3,), dtype=int32)


In [ ]:
tensor_indexed = tf.constant([3,6,2,4,6,66,7])
print(tensor_indexed)
print(tensor_indexed[0:4])
print(tensor_indexed[1:5])
print(tensor_indexed[1:6])
print(tensor_indexed[1:6:2])
print(tensor_indexed[3:])
print(tensor_indexed[3:-3])

tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)
tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)
tf.Tensor([6 2 4 6], shape=(4,), dtype=int32)
tf.Tensor([ 6  2  4  6 66], shape=(5,), dtype=int32)
tf.Tensor([ 6  4 66], shape=(3,), dtype=int32)
tf.Tensor([ 4  6 66  7], shape=(4,), dtype=int32)
tf.Tensor([4], shape=(1,), dtype=int32)


In [ ]:
tf.range(2, 5)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4], dtype=int32)>

In [ ]:
tensor_two_d = tf.constant([
                            [1,2,0],
                            [3,5,-1],
                            [1,5,5],
                            [2,3,8]
                            ])
print(tensor_two_d[0:3,0:2])
print(tensor_two_d[0:3,:])
print(tensor_two_d[2,:])
print(tensor_two_d[:,1])
print(tensor_two_d[...,1])

tf.Tensor(
[[1 2]
 [3 5]
 [1 5]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  5]], shape=(3, 3), dtype=int32)
tf.Tensor([1 5 5], shape=(3,), dtype=int32)
tf.Tensor([2 5 5 3], shape=(4,), dtype=int32)
tf.Tensor([2 5 5 3], shape=(4,), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
                             [[1,2,0],
                              [3,5,-1]],

                             [[10,2,0],
                              [1,0,2]],

                             [[5,8,0],
                              [2,7,0]],

                             [[2,1,9],
                              [4,-3,32]]
                             ])
print(tensor_three_d[0,:,:])
print(tensor_three_d[0,0,:])
print(tensor_three_d[0,0,-1])
print(tensor_three_d[0:2,:,2])
print(tensor_three_d[0:2,...,2])
print(tensor_three_d[...,:,2])

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]], shape=(2, 3), dtype=int32)
tf.Tensor([1 2 0], shape=(3,), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(
[[ 0 -1]
 [ 0  2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 0 -1]
 [ 0  2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 0 -1]
 [ 0  2]
 [ 0  0]
 [ 9 32]], shape=(4, 2), dtype=int32)


In [ ]:
x_abs = tf.constant([-2.25,3.25])
tf.abs(x_abs)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [ ]:
tf.abs(tf.constant(-0.2))

<tf.Tensor: shape=(), dtype=float32, numpy=0.20000000298023224>

In [ ]:
tf.abs(tf.constant(0.2))

<tf.Tensor: shape=(), dtype=float32, numpy=0.20000000298023224>

In [ ]:
x_abs_complex = tf.constant([-2.25 + 4.75j])
tf.abs(x_abs_complex)

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([5.25594901])>

In [ ]:
tf.sqrt((-2.25) ** 2  + 4.75**2)

<tf.Tensor: shape=(), dtype=float32, numpy=5.255949020385742>

In [ ]:
x_1 = tf.constant([5,3,6,6,4,6], dtype = tf.int32)
x_2 = tf.constant([7,6,2,6,0,11], dtype = tf.int32)
print(tf.add(x_1,x_2))
print(tf.multiply(x_1,x_2))
print(tf.subtract(x_1,x_2))
print(tf.divide(x_1,x_2))
print(tf.math.divide_no_nan(x_1,x_2))

tf.Tensor([12  9  8 12  4 17], shape=(6,), dtype=int32)
tf.Tensor([35 18 12 36  0 66], shape=(6,), dtype=int32)
tf.Tensor([-2 -3  4  0  4 -5], shape=(6,), dtype=int32)
tf.Tensor([0.71428571 0.5        3.         1.                inf 0.54545455], shape=(6,), dtype=float64)
tf.Tensor([0.71428571 0.5        3.         1.         0.         0.54545455], shape=(6,), dtype=float64)


In [ ]:
x_1 = tf.constant([5,3,6,6,4,6], dtype = tf.int32)
x_2 = tf.constant([7], dtype = tf.int32)
print(tf.math.add(x_1,x_2))

tf.Tensor([12 10 13 13 11 13], shape=(6,), dtype=int32)


In [ ]:
x_1 = tf.constant([5,3,6,6,4,6], dtype = tf.int32)
x_2 = tf.constant([7], dtype = tf.int32)
x_2_stretched= tf.constant([7,7,7,7,7,7], dtype = tf.int32)
print(tf.math.add(x_1,x_2).shape)
print(tf.math.add(x_1,x_2_stretched))

(6,)
tf.Tensor([12 10 13 13 11 13], shape=(6,), dtype=int32)


In [ ]:
x_1 = tf.constant([
                   [5,3,6,6,4,6],
                   [5,45,65,5,53,4]
                  ], dtype = tf.float32)
x_2 = tf.constant([7], dtype = tf.float32)
x_2_stretched= tf.constant([7,7,7,7,7,7], dtype = tf.float32)
print(tf.math.add(x_1,x_2).shape)
print(tf.math.add(x_1,x_2_stretched))

(2, 6)
tf.Tensor(
[[12. 10. 13. 13. 11. 13.]
 [12. 52. 72. 12. 60. 11.]], shape=(2, 6), dtype=float32)


In [ ]:
x_1 = tf.constant([
                   [5,3,6,6,4,6],
                   [5,45,65,5,53,4]
                  ], dtype = tf.float32)
x_2 = tf.constant([7], dtype = tf.float32)
x_2_stretched= tf.constant([7,7,7,7,7,7], dtype = tf.float32)
print(tf.math.add(x_1,x_2))
print(tf.math.add(x_1,x_2_stretched))

tf.Tensor(
[[12. 10. 13. 13. 11. 13.]
 [12. 52. 72. 12. 60. 11.]], shape=(2, 6), dtype=float32)
tf.Tensor(
[[12. 10. 13. 13. 11. 13.]
 [12. 52. 72. 12. 60. 11.]], shape=(2, 6), dtype=float32)


In [ ]:
x_1 = tf.constant([[5,3,6,6,4,6],[5,45,65,5,53,4]
                  ], dtype = tf.float32)
x_2 = tf.constant([7], dtype = tf.float32)
x_2_stretched= tf.constant([7,7,7,7,7,7], dtype = tf.float32)
print(tf.math.multiply(x_1,x_2))
print(tf.math.multiply(x_1,x_2_stretched))

tf.Tensor(
[[ 35.  21.  42.  42.  28.  42.]
 [ 35. 315. 455.  35. 371.  28.]], shape=(2, 6), dtype=float32)
tf.Tensor(
[[ 35.  21.  42.  42.  28.  42.]
 [ 35. 315. 455.  35. 371.  28.]], shape=(2, 6), dtype=float32)


In [ ]:
x_1 = tf.constant([[5,3,6,6,4,6],], dtype = tf.float32)
x_2 = tf.constant([7], dtype = tf.float32)
x_2_stretched= tf.constant([7,7,7,7,7,7], dtype = tf.float32)
print(tf.math.multiply(x_1,x_2))
print(tf.math.multiply(x_1,x_2_stretched))

tf.Tensor([[35. 21. 42. 42. 28. 42.]], shape=(1, 6), dtype=float32)
tf.Tensor([[35. 21. 42. 42. 28. 42.]], shape=(1, 6), dtype=float32)


In [ ]:
x_1 = tf.constant([[5,3,6,6,4,6],], dtype = tf.float32)
x_2 = tf.constant([[7], [5], [3]], dtype = tf.float32)

print(tf.math.multiply(x_1,x_2))
print(tf.math.multiply(x_1,x_2_stretched))

tf.Tensor(
[[35. 21. 42. 42. 28. 42.]
 [25. 15. 30. 30. 20. 30.]
 [15.  9. 18. 18. 12. 18.]], shape=(3, 6), dtype=float32)
tf.Tensor([[35. 21. 42. 42. 28. 42.]], shape=(1, 6), dtype=float32)


In [ ]:
x_1 = tf.constant([[5,3,6,6,4,6],], dtype = tf.float32)
x_2 = tf.constant([[7], [5], [3]], dtype = tf.float32)

print(x_1.shape)
print(x_2.shape)
print(tf.math.multiply(x_1,x_2))


(1, 6)
(3, 1)
tf.Tensor(
[[35. 21. 42. 42. 28. 42.]
 [25. 15. 30. 30. 20. 30.]
 [15.  9. 18. 18. 12. 18.]], shape=(3, 6), dtype=float32)


In [ ]:
x_argmax = tf.constant([[2, 20, 30, 3, 6],
                        [3, 11, 16, 1, 8],
                        [14, 45, 23, 5, 27]])
print(x_argmax.shape)

(3, 5)


In [ ]:
x_argmax = tf.constant([[2, 20, 30, 3, 6],
                        [3, 11, 16, 1, 8],
                        [14, 45, 23, 5, 27]])
print(x_argmax.shape)

print(tf.math.argmax(x_argmax, 0))

print(tf.math.argmin(x_argmax, axis = 0))
print(tf.math.argmin(x_argmax, axis = 1))

(3, 5)
tf.Tensor([2 2 0 2 2], shape=(5,), dtype=int64)
tf.Tensor([0 1 1 1 0], shape=(5,), dtype=int64)
tf.Tensor([0 3 3], shape=(3,), dtype=int64)


In [ ]:
x_argmax = tf.constant([2, 20, 30, 3, 6])
print(tf.math.argmax(x_argmax))

tf.Tensor(2, shape=(), dtype=int64)


In [ ]:
x_argmax = tf.constant([200, 120, 130, 300, 6])
print(tf.math.argmin(x_argmax))

tf.Tensor(4, shape=(), dtype=int64)


In [ ]:
x_argmax = tf.constant([200, 120, 130, 300, 6])
print(tf.math.argmin(x_argmax))

tf.Tensor(4, shape=(), dtype=int64)


In [ ]:
x = tf.constant([[2,2], [3,3]])
y = tf.constant([[8,16],[2,3]])
tf.pow(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  256, 65536],
       [    9,    27]], dtype=int32)>

In [ ]:
tf.pow(tf.constant(2), tf.constant(3))

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [ ]:
tensor_two_d = tf.constant([
                            [1,2,0],
                            [3,5,-1],
                            [1,5,6],
                            [2,3,8]
                            ])
print(tf.math.reduce_sum(tensor_two_d, axis=None, keepdims=False, name=None))

tf.Tensor(35, shape=(), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([
                            [1,2,0],
                            [3,5,-1],
                            [1,5,6],
                            [2,3,8]
                            ])
print(tf.math.reduce_max(tensor_two_d, axis=None, keepdims=False, name=None))

tf.Tensor(8, shape=(), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([
                            [1,2,0],
                            [3,5,-1],
                            [1,5,6],
                            [2,3,8]
                            ])
print(tf.math.reduce_min(tensor_two_d, axis=None, keepdims=False, name=None))

tf.Tensor(-1, shape=(), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([
                            [1,2,0],
                            [3,5,-1],
                            [1,5,6],
                            [2,3,8]
                            ])
print(tensor_two_d)
print(tf.math.reduce_sum(tensor_two_d, axis=0, keepdims=False, name=None))

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)
tf.Tensor([ 7 15 13], shape=(3,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([
                            [1,2,0],
                            [3,5,-1],
                            [1,5,6],
                            [2,3,8]
                            ])
print(tensor_two_d)
print(tf.math.reduce_sum(tensor_two_d, axis=1, keepdims=False, name=None))

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)
tf.Tensor([ 3  7 12 13], shape=(4,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([
                            [1,2,0],
                            [3,5,100],
                            [1,5,6],
                            [2,3,8]
                            ])
print(tf.math.reduce_max(tensor_two_d, axis=1, keepdims=False, name=None))

tf.Tensor([  2 100   6   8], shape=(4,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([
                            [1,-2,0],
                            [3,5,100],
                            [1,5,6],
                            [2,3,8]
                            ])
print(tf.math.reduce_mean(tensor_two_d, axis=1, keepdims=False, name=None))

tf.Tensor([ 0 36  4  4], shape=(4,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([
                            [1,2,0],
                            [3,5,-1],
                            [1,5,6],
                            [2,3,8]
                            ], dtype = tf.float16)
print(tf.math.reduce_mean(tensor_two_d, axis=0, keepdims=False, name=None))

tf.Tensor([1.75 3.75 3.25], shape=(3,), dtype=float16)


In [ ]:
tensor_two_d = tf.constant([
                            [1,2,0],
                            [3,5,-1],
                            [1,5,6],
                            [2,3,8]
                            ], dtype = tf.float16)
print(tf.math.reduce_mean(tensor_two_d, axis=0, keepdims=True, name=None))

tf.Tensor([[1.75 3.75 3.25]], shape=(1, 3), dtype=float16)


In [ ]:
tf.math.top_k(tensor_two_d)

TopKV2(values=<tf.Tensor: shape=(4, 1), dtype=float16, numpy=
array([[2.],
       [5.],
       [6.],
       [8.]], dtype=float16)>, indices=<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[1],
       [1],
       [2],
       [2]], dtype=int32)>)

In [ ]:
tf.math.top_k(tensor_two_d, k = 1)

TopKV2(values=<tf.Tensor: shape=(4, 1), dtype=float16, numpy=
array([[2.],
       [5.],
       [6.],
       [8.]], dtype=float16)>, indices=<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[1],
       [1],
       [2],
       [2]], dtype=int32)>)

In [ ]:
tf.math.top_k(tensor_two_d, k = 2)

TopKV2(values=<tf.Tensor: shape=(4, 2), dtype=float16, numpy=
array([[2., 1.],
       [5., 3.],
       [6., 5.],
       [8., 3.]], dtype=float16)>, indices=<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 0],
       [1, 0],
       [2, 1],
       [2, 1]], dtype=int32)>)

In [ ]:
x_1 = tf.constant([[1,2,0],
                   [3,5,-1]])
x_2 = tf.constant([[1,2,0],
                   [3,5,-1],
                   [4,5,6]])
print(x_1.shape, x_2.shape)
tf.linalg.matmul(
    x_1, x_2, transpose_a = False,transpose_b = False, adjoint_a = False, adjoint_b = False,
    a_is_sparse = False, b_is_sparse = False, output_type=None, name=None
)

(2, 3) (3, 3)


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[  7,  12,  -2],
       [ 14,  26, -11]], dtype=int32)>

In [ ]:
x_1 = tf.constant([[1,2,0]])

x_2 = tf.constant([[1,2,0,2],
                   [3,5,-1,2],
                   [4,5,6,0]])
print(x_1.shape, x_2.shape)
tf.linalg.matmul(
    x_1, x_2, transpose_a = False,transpose_b = False, adjoint_a = False, adjoint_b = False,
    a_is_sparse = False, b_is_sparse = False, output_type=None, name=None
)

(1, 3) (3, 4)


<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[ 7, 12, -2,  6]], dtype=int32)>

In [ ]:
print(x_1 @ x_2)

tf.Tensor([[ 7 12 -2  6]], shape=(1, 4), dtype=int32)


In [ ]:
tf.transpose(x_1)

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[1],
       [2],
       [0]], dtype=int32)>

In [ ]:
print(x_1)

tf.Tensor([[1 2 0]], shape=(1, 3), dtype=int32)


In [ ]:
tf.transpose(x_2)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  3,  4],
       [ 2,  5,  5],
       [ 0, -1,  6],
       [ 2,  2,  0]], dtype=int32)>

In [ ]:
print(x_2)

tf.Tensor(
[[ 1  2  0  2]
 [ 3  5 -1  2]
 [ 4  5  6  0]], shape=(3, 4), dtype=int32)


In [ ]:
x_1 = tf.constant([[1,2,0]])

x_2 = tf.constant([[1,2,0,2],
                   [3,5,-1,2],
                   [4,5,6,0]])

x_3 = tf.constant([[1,2,0,2],
                   [3,5,-1,2]])

print(x_1.shape, x_2.shape, x_3.shape, tf.transpose(x_2).shape)
tf.linalg.matmul(
    x_1, x_2, transpose_a = False,transpose_b = False, adjoint_a = False, adjoint_b = False,
    a_is_sparse = False, b_is_sparse = False, output_type=None, name=None
)

(1, 3) (3, 4) (2, 4) (4, 3)


<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[ 7, 12, -2,  6]], dtype=int32)>

In [ ]:
print(x_3 @ tf.transpose(x_2))

tf.Tensor(
[[ 9 17 14]
 [17 39 31]], shape=(2, 3), dtype=int32)


In [ ]:
x_1 = tf.constant([[1,2,0]])

x_2 = tf.constant([[1,2],
                   [3,5],
                   [4,5]])

x_3 = tf.constant([[1,2,0,2],
                   [3,5,-1,2]])

print(x_1.shape, x_2.shape, x_3.shape, tf.transpose(x_2).shape)

print(tf.transpose(x_3)@tf.transpose(x_2))

tf.linalg.matmul(
    x_3, x_2, transpose_a = True,transpose_b = True, adjoint_a = False, adjoint_b = False,
    a_is_sparse = False, b_is_sparse = False, output_type=None, name=None
)

(1, 3) (3, 2) (2, 4) (2, 3)
tf.Tensor(
[[ 7 18 19]
 [12 31 33]
 [-2 -5 -5]
 [ 6 16 18]], shape=(4, 3), dtype=int32)


<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 7, 18, 19],
       [12, 31, 33],
       [-2, -5, -5],
       [ 6, 16, 18]], dtype=int32)>

In [ ]:
x_1 = tf.constant([[[1,2,0],
                    [3,5,-1]],

                   [[10,2,0],
                    [1,0,2]],

                   [[5,8,0],
                    [2,7,0]]])

x_2 = tf.constant([[[5,1,4],
                    [34,15,1]],

                   [[1,2,2],
                    [5,3,2]],

                   [[2,2,3],
                    [1,1,1]]])
print(x_1)
print(x_2)

print(tf.linalg.matmul(x_1,x_2))

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]], shape=(3, 2, 3), dtype=int32)
tf.Tensor(
[[[ 5  1  4]
  [34 15  1]]

 [[ 1  2  2]
  [ 5  3  2]]

 [[ 2  2  3]
  [ 1  1  1]]], shape=(3, 2, 3), dtype=int32)


InvalidArgumentError: {{function_node __wrapped__BatchMatMulV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2,3], In[1]: [3,2,3] [Op:BatchMatMulV2] name: 

In [ ]:
x_1 = tf.constant([[[1,2],
                    [3,5]],

                   [[10,2],
                    [1,0]],

                   [[5,8],
                    [2,7]]])

x_2 = tf.constant([[[5,1,4],
                    [34,15,1]],

                   [[1,2,2],
                    [5,3,2]],

                   [[2,2,3],
                    [1,1,1]]])
print(x_1)
print(x_2)

print(tf.linalg.matmul(x_1,x_2))

tf.Tensor(
[[[ 1  2]
  [ 3  5]]

 [[10  2]
  [ 1  0]]

 [[ 5  8]
  [ 2  7]]], shape=(3, 2, 2), dtype=int32)
tf.Tensor(
[[[ 5  1  4]
  [34 15  1]]

 [[ 1  2  2]
  [ 5  3  2]]

 [[ 2  2  3]
  [ 1  1  1]]], shape=(3, 2, 3), dtype=int32)
tf.Tensor(
[[[ 73  31   6]
  [185  78  17]]

 [[ 20  26  24]
  [  1   2   2]]

 [[ 18  18  23]
  [ 11  11  13]]], shape=(3, 2, 3), dtype=int32)


In [ ]:
x_1 = tf.constant([ [10,0],
                    [1,2]])

x_2 = tf.constant([ [1,2,2],
                    [5,3,2]])
print(x_1)
print(x_2)

print(tf.linalg.matmul(x_1,x_2))

tf.Tensor(
[[10  0]
 [ 1  2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 2 2]
 [5 3 2]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[10 20 20]
 [11  8  6]], shape=(2, 3), dtype=int32)


In [25]:
tensor_two_d = tf.constant([[1,-2,0],
                            [3,5,100],
                            [1,5,6],
                            [2,3,8]], dtype = tf.float16)
tensor_out_d = tf.constant([[1,0,0],
                            [0,5,0],
                            [0,0,6],
                            [0,0,0]], dtype = tf.float16)
tf.linalg.band_part(tensor_two_d, 0,0)


<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 6.],
       [0., 0., 0.]], dtype=float16)>

In [26]:
tensor_two_d = tf.constant([[1,-2,0],
                            [3,5,100],
                            [1,5,6],
                            [2,3,8]], dtype = tf.float16)
tensor_out_d = tf.constant([[1,0,0],
                            [0,5,0],
                            [0,0,6],
                            [0,0,0]], dtype = tf.float16)
tf.linalg.band_part(tensor_two_d, -1,0)


<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[1., 0., 0.],
       [3., 5., 0.],
       [1., 5., 6.],
       [2., 3., 8.]], dtype=float16)>

In [27]:
tensor_two_d = tf.constant([[1,-2,0],
                            [3,5,100],
                            [1,5,6],
                            [2,3,8]], dtype = tf.float16)
tensor_out_d = tf.constant([[1,0,0],
                            [0,5,0],
                            [0,0,6],
                            [0,0,0]], dtype = tf.float16)
tf.linalg.band_part(tensor_two_d, 0,-1)


<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[  1.,  -2.,   0.],
       [  0.,   5., 100.],
       [  0.,   0.,   6.],
       [  0.,   0.,   0.]], dtype=float16)>

In [28]:
tensor_two_d = tf.constant([[1,-2,0],
                            [3,5,100],
                            [1,5,6],
                            [2,3,8]], dtype = tf.float32)
tf.linalg.inv(tensor_two_d)

InvalidArgumentError: {{function_node __wrapped__MatrixInverse_device_/job:localhost/replica:0/task:0/device:CPU:0}} Input matrix must be square. [Op:MatrixInverse] name: 

In [30]:
tensor_two_d = tf.constant([[1,-2,0],
                            [3,5,100],
                            [1,5,6]], dtype = tf.float32)
tensor_two_d_inv = tf.linalg.inv(tensor_two_d)

In [31]:
tensor_two_d @ tensor_two_d_inv

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.0000000e+00,  7.4505806e-09,  0.0000000e+00],
       [ 1.6391277e-07,  1.0000000e+00,  4.4703484e-08],
       [-5.2154064e-08,  7.4505806e-08,  1.0000000e+00]], dtype=float32)>